//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DllForGame.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_EXE_DIALOG                  102
#define IDD_NULL                        131
#define IDD_PROP_SEL_USER               132
#define IDD_USER_LIST                   133
#define IDD_DIY_CHAT                    134
#define IDD_GETPOINT                    135
#define IDD_CONFIRMDLG                  136
#define IDD_SHOW_LEFT                   137
#define IDD_SHORT_MESSAGE               138
#define IDD_SHOWSCORE                   139
#define IDI_CLIENT_LIST                 141
#define IDI_ICON2                       142
#define IDI_CLIENT_ROOM                 142
#define IDD_NT_LIST                     143

//wushuqun 2009.7.17
//手形鼠标不用，用系统默认的, 不然会有些游戏找不到这个光标
//#define IDC_HAND                        143

#define IDD_BEGIN_ANIMAL                144
#define IDC_PROP_SEL                    144
#define IDD_END_ANIMAL                  145
#define IDD_NOTE_ANIMAL                 146
#define IDD_EASY_LIST                   147
#define IDD_THING                       148
#define IDD_SHOW_NOTE                   149
#define IDD_GAME_END                    150
#define IDC_CANCEL                      151
#define IDD_STOP_MESSAGE                151
#define IDC_OK                          152
#define IDD_BACK_CARD                   152
#define IDD_STOP                        153
#define IDD_THING_MESSAGE               154
#define BUTTON_MOVE                     155
#define SYSTEM_MSG                      156
#define WARN                            157
#define IDC_1                           158
#define IDD_MJSET                       158
#define IDC_2                           159
#define IDD_DIALOG1                     159
#define IDD_FLASH_DLG                   159
#define IDC_3                           160
#define IDR_WAVE1                       160
#define BUTTON_UP                       160
#define IDC_4                           161
#define IDC_5                           162
#define IDC_6                           163
#define IDC_7                           164
#define IDC_8                           165
#define IDC_9                           166
#define IDC_10                          167
#define IDC_11                          168
#define IDC_12                          169
#define IDC_BEGIN                       170
#define IDC_SHOW                        171
#define IDC_FOLLOW                      172
#define IDC_NOTE                        173
#define IDC_GIVEUP                      174
#define IDC_LOOK                        175
#define IDC_LEAVE_MSG                   176
#define IDC_LEFT_USER                   177
#define IDC_THING                       178
#define IDC_SOUND                       179
#define IDC_USER_MESSAGE                180
#define IDC_RIGHT_POWER                 181
#define IDC_WATCH                       182
#define IDD_GAME_SET                    183
#define IDB_GAME_CARD                   184
#define IDD_PROPPANNEL                  185
#define IDD_BOARDCAST                   186
#define IDB_LOST_LOGO                   230
#define IDB_EP_001                      501
#define IDB_EP_002                      502
#define IDB_EP_003                      503
#define IDB_EP_004                      504
#define IDB_EP_005                      505
#define IDB_EP_006                      506
#define IDB_EP_007                      507
#define IDB_EP_008                      508
#define IDB_EP_009                      509
#define IDB_EP_010                      510
#define IDB_EP_011                      511
#define IDB_EP_012                      512
#define IDB_EP_013                      513
#define IDB_EP_014                      514
#define IDB_EP_015                      515
#define IDB_EP_016                      516
#define IDB_EP_017                      517
#define IDB_EP_018                      518
#define IDB_EP_019                      519
#define IDB_EP_020                      520
#define IDB_EP_021                      521
#define IDB_EP_022                      522
#define IDB_EP_023                      523
#define IDB_EP_024                      524
#define IDB_EP_025                      525
#define IDB_EP_026                      526
#define IDB_EP_027                      527
#define IDB_EP_028                      528
#define IDB_EP_029                      529
#define IDB_EP_030                      530
#define IDB_EP_031                      531
#define IDB_EP_032                      532
#define IDB_EP_033                      533
#define IDB_EP_034                      534
#define IDB_EP_035                      535
#define IDB_EP_036                      536
#define IDB_EP_037                      537
#define IDB_EP_038                      538
#define IDB_EP_039                      539
#define IDB_EP_040                      540
#define IDB_EP_041                      541
#define IDB_EP_042                      542
#define IDB_EP_043                      543
#define IDB_EP_044                      544
#define IDB_EP_045                      545
#define IDB_EP_046                      546
#define IDB_EP_047                      547
#define IDB_EP_048                      548
#define IDB_EP_049                      549
#define IDB_EP_050                      550
#define IDB_EP_051                      551
#define IDB_EP_052                      552
#define IDB_EP_053                      553
#define IDB_EP_054                      554
#define IDB_EP_055                      555
#define IDB_EP_056                      556
#define IDB_EP_057                      557
#define IDB_EP_058                      558
#define IDB_EP_059                      559
#define IDB_EP_060                      560
#define IDB_EP_061                      561
#define IDB_EP_062                      562
#define IDB_EP_063                      563
#define IDB_EP_064                      564
#define IDB_EP_065                      565
#define IDB_EP_066                      566
#define IDB_EP_067                      567
#define IDB_EP_068                      568
#define IDB_MATCH_LOGO                  569
#define IDD_CARD_SET                    570
#define IDC_HEITAO_1                    571
#define IDC_HEITAO_2                    572
#define IDC_HEITAO_3                    573
#define IDC_HEITAO_4                    574
#define IDC_HEITAO_5                    575
#define IDC_HEITAO_6                    576
#define IDC_HEITAO_7                    577
#define IDC_HEITAO_8                    578
#define IDC_HEITAO_9                    579
#define IDC_HEITAO_10                   580
#define IDC_HEITAO_J                    581
#define IDC_HEITAO_Q                    582
#define IDC_HEITAO_K                    583
#define IDC_HONGTAO_1                   584
#define IDC_HONGTAO_2                   585
#define IDC_HONGTAO_3                   586
#define IDC_HONGTAO_4                   587
#define IDC_HONGTAO_5                   588
#define IDC_HONGTAO_6                   589
#define IDC_HONGTAO_7                   590
#define IDC_HONGTAO_8                   591
#define IDC_HONGTAO_9                   592
#define IDC_HONGTAO_10                  593
#define IDC_HONGTAO_J                   594
#define IDC_HONGTAO_Q                   595
#define IDC_HONGTAO_K                   596
#define IDC_MEIHUA_1                    597
#define IDC_MEIHUA_2                    598
#define IDC_MEIHUA_3                    599
#define IDC_MEIHUA_4                    600
#define IDC_MEIHUA_5                    601
#define IDC_MEIHUA_6                    602
#define IDC_MEIHUA_7                    603
#define IDC_MEIHUA_8                    604
#define IDC_MEIHUA_9                    605
#define IDC_MEIHUA_10                   606
#define IDC_MEIHUA_J                    607
#define IDC_MEIHUA_Q                    608
#define IDC_MEIHUA_K                    609
#define IDC_FANGKUAI_1                  610
#define IDC_FANGKUAI_2                  611
#define IDC_FANGKUAI_3                  612
#define IDC_FANGKUAI_4                  613
#define IDC_FANGKUAI_5                  614
#define IDC_FANGKUAI_6                  615
#define IDC_FANGKUAI_7                  616
#define IDC_FANGKUAI_8                  617
#define IDC_FANGKUAI_9                  618
#define IDC_FANGKUAI_10                 619
#define IDC_FANGKUAI_J                  620
#define IDC_FANGKUAI_Q                  621
#define IDC_FANGKUAI_K                  622
#define IDC_WANG_1                      623
#define IDC_WANG_2                      624
#define IDC_CARD_1                      625
#define IDC_CARD_2                      626
#define IDC_CARD_3                      627
#define IDC_CARD_4                      628
#define IDC_DESK_0                      629
#define IDC_DESK_1                      630
#define IDC_DESK_2                      631
#define IDC_DESK_3                      632
#define IDC_DESK_4                      633
#define IDC_DESK_5                      634
#define IDC_DESK_6                      635
#define IDC_NICHENG                     636
#define IDC_MENGPAI                     637
#define IDC_ZMR                         638
#define IDC_CHENGHAO                    639
#define IDC_CAIFU                       640
#define IDC_JIFENG                      641
#define IDC_JIBIE                       642
#define IDC_CHAT                        643
#define IDC_INVITE_PLAY                 644
#define IDC_WATCH_GAME                  645
#define IDC_GIFT                        646
#define IDD_PERSONINFO                  647
#define IDC_FALSH                       648
#define IDC_MENU                        649
#define IDC_TALK_MESSAGE                1000
#define IDC_EXPLORER1                   1002
#define IDC_GO_AHEAD                    1003
#define IDC_BUTTON_PROP1                1004
#define IDC_BUTTON_PROP2                1005
#define IDC_BUTTON_PROP3                1006
#define IDC_GO_NEXT                     1008
#define IDC_EXPRESSION                  1009
#define IDC_SETCOLOR                    1010
#define IDC_SEND                        1011
#define IDC_INPUT                       1012
#define IDC_HOR_SPLIT                   1013
#define IDC_HIDE                        1014
#define IDC_GAME_BTN_01                 1015
#define IDC_GAME_BTN_02                 1016
#define IDC_GAME_BTN_03                 1017
#define IDC_MODIFY                      1017
#define IDC_GAME_BTN_04                 1018
#define IDC_ADD                         1018
#define IDC_GAME_BTN_05                 1019
#define IDC_GAME_BTN_06                 1020
#define IDC_GAME_BTN_07                 1021
#define IDC_BUTTON_PROP4                1022
#define IDC_GAME_BTN_09                 1023
#define IDC_GAME_BTN_10                 1024
#define IDC_SNDVOLDOWN                  1025
#define IDC_SNDPAUSE                    1026
#define IDC_SNDPLAY                     1027
#define IDC_SNDVOLUP                    1028
#define IDC_MIN                         1029
#define IDC_MAX                         1030
#define IDC_REST                        1031
#define IDC_EXIT                        1032
#define IDC_QUIT_GAME                   1033
#define IDC_CLOSE                       1034
#define IDC_USER_LIST                   1035
#define IDC_LIST_CHAT                   1036
#define IDC_EDIT1                       1037
#define IDC_DELETE                      1038
#define IDC_POINT                       1039
#define IDC_SERPOINT                    1040
#define IDC_STATIC_PIC                  1041
#define IDQUXIAO                        1042
#define IDC_CLOSEBTN                    1043
#define IDC_TIME                        1044
#define IDC_LEFT_NAME                   1045
#define IDC_RECV_MESSAGE                1046
#define IDC_SEND_MESSAGE                1047
#define IDC_CLOSESM                     1048
#define IDC_SEND_SHORT                  1049
#define IDC_INFORSTR                    1050
#define IDC_LIST1                       1051
#define IDC_SCORE_LIST                  1051
#define IDC_SELECT_COLOR                1052
#define IDC_EDIT_INPUT                  1053
#define IDC_STATIC_PROMPT               1054
#define IDC_USE                         1055
#define IDC_BUY                         1056
#define IDC_GIVE                        1057
#define IDC_HOLDCOUNT                   1058
#define IDC_NEEDMONEY                   1059
#define IDC_BUYCOUNT                    1060
#define IDC_GIVEUSER                    1061
#define IDC_GIVECOUNT                   1062
#define IDC_TIP                         1063
#define IDC_DENG                        2073
#define IDC_HCUR                        10980
#define IDC_VCUR                        10981
#define IDC_DIS                         10982
#define IDC_WAN_1                       20037
#define IDC_WAN_2                       20038
#define IDC_WAN_3                       20039
#define IDC_WAN_4                       20040
#define IDC_WAN_5                       20041
#define IDC_WAN_6                       20042
#define IDC_WAN_7                       20043
#define IDC_WAN_8                       20044
#define IDC_WAN_9                       20045
#define IDC_BIN_1                       20055
#define IDC_BIN_2                       20056
#define IDC_BIN_3                       20057
#define IDC_BIN_4                       20058
#define IDC_BIN_5                       20059
#define IDC_BIN_6                       20060
#define IDC_BIN_7                       20061
#define IDC_BIN_8                       20062
#define IDC_BIN_9                       20063
#define IDC_TIAO_1                      20064
#define IDC_TIAO_2                      20065
#define IDC_TIAO_3                      20066
#define IDC_TIAO_4                      20067
#define IDC_TIAO_5                      20068
#define IDC_TIAO_6                      20069
#define IDC_TIAO_7                      20070
#define IDC_TIAO_8                      20071
#define IDC_TIAO_9                      20072
#define IDC_NAN                         20074
#define IDC_XI                          20075
#define IDC_BEI                         20076
#define IDC_ZHONG                       20077
#define IDC_FA                          20078
#define IDC_BAI                         20079
#define IDC_CUN                         20080
#define IDC_XIA                         20081
#define IDC_QIU                         20082
#define IDC_DONG                        20083
#define IDC_MEI                         20084
#define IDC_LAN                         20085
#define IDC_ZHU                         20086
#define IDC_JU                          20087
#define IDC_MJDESK_0                    20088
#define IDC_MJDESK_1                    20089
#define IDC_MJDESK_2                    20090
#define IDC_MJDESK_3                    20091
#define IDC_MJDESK_4                    20092
#define IDC_MJDESK_5                    20093
#define IDC_MJDESK_6                    20094
#define IDM_FIND_ONLINE_USER            32678
#define IDM_FIND_DESK                   32680
#define IDM_CUSTOM_FIND_DESK            32681
#define IDM_FINDED_SIT                  32682
#define IDM_TALK_COLOR                  32693
#define IDM_RED                         32694
#define IDM_YELLOW                      32695
#define IDM_BULE                        32696
#define IDM_GREEN                       32697
#define IDM_WHITE                       32698
#define IDM_POWER_RED                   32699
#define IDM_GRAY                        32700
#define IDM_SAVE_MESSAGE                32701
#define IDM_CLEAR_SCREEN                32703
#define IDM_AUTO_SCROLL                 32704
#define IDM_GIVE_PROP                   32705
#define IDM_GAME_RULE                   32786
#define IDM_JOIN_GAME                   32787

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        161
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         1052
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
