//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GameClient.rc
//
#define IDR_MANIFEST                    1
#define IDD_THING                       132
#define IDC_CURSOR                      133
#define IDD_THING_MESSAGE               134
#define IDD_GAME_END                    135
#define IDD_GAME_NOTE                   137
#define IDD_DISPLAY_TALK                138
#define IDD_LOSE                        139
#define IDD_LOSE_MESSAGE                140
#define IDD_NT_LIST                     143
#define IDD_SET_PLAY                    157
#define IDD_GAME_INFO                   158
#define IDD_GAME_SET                    254
#define IDC_BEGIN                       1000
#define IDC_THREE                       1000
#define IDI_CLIENT_LIST                 1000
#define IDI_CLIENT_ROOM                 1001
#define IDC_SHOW_HAND                   1001
#define IDC_TWO                         1001
#define IDC_FOLLOW                      1002
#define IDC_BEGIN_STATION               1002
#define IDC_MESSAGE                     1002
#define IDC_GIVE_UP                     1003
#define IDC_POINT_1                     1004
#define IDC_POINT_5                     1005
#define IDC_POINT_10                    1006
#define IDC_POINT_50                    1007
#define IDC_SPIN                        1007
#define IDC_POINT_100                   1008
#define IDC_POINT_500                   1009
#define IDC_END_STATION                 1009
#define IDC_SELECT                      1010
#define IDC_NO_CONTINUE                 1010
#define IDC_EDIT1                       1011
#define IDC_1                           1013
#define IDC_LEFT_USER                   1014
#define IDC_COUNT                       1014
#define IDC_3                           1014
#define IDC_LEAVE_MSG                   1015
#define IDC_4                           1015
#define IDC_2                           1016
#define IDC_NT                          1017
#define IDC_FEN                         1018
#define IDC_LIST2                       1019
#define IDC_MSG                         1019
#define IDC_BK_SOUND                    1022
#define IDC_SOUND                       1023
#define IDC_WATCH                       1024
#define IDD_STOP                        1024
#define IDC_USER_MESSAGE                1025
#define IDD_STOP_MESSAGE                1025
#define IDC_RICHEDIT21                  1025
#define IDC_RIGHT_POWER                 1026
#define IDC_RADIO1                      1027
#define IDC_ONECARD                     1047
#define IDC_THING                       1063

#define IDD_CARD_SET                    570
#define IDC_HEITAO_1                    571
#define IDC_HEITAO_2                    572
#define IDC_HEITAO_3                    573
#define IDC_HEITAO_4                    574
#define IDC_HEITAO_5                    575
#define IDC_HEITAO_6                    576
#define IDC_HEITAO_7                    577
#define IDC_HEITAO_8                    578
#define IDC_HEITAO_9                    579
#define IDC_HEITAO_10                   580
#define IDC_HEITAO_J                    581
#define IDC_HEITAO_Q                    582
#define IDC_HEITAO_K                    583
#define IDC_HONGTAO_1                   584
#define IDC_HONGTAO_2                   585
#define IDC_HONGTAO_3                   586
#define IDC_HONGTAO_4                   587
#define IDC_HONGTAO_5                   588
#define IDC_HONGTAO_6                   589
#define IDC_HONGTAO_7                   590
#define IDC_HONGTAO_8                   591
#define IDC_HONGTAO_9                   592
#define IDC_HONGTAO_10                  593
#define IDC_HONGTAO_J                   594
#define IDC_HONGTAO_Q                   595
#define IDC_HONGTAO_K                   596
#define IDC_MEIHUA_1                    597
#define IDC_MEIHUA_2                    598
#define IDC_MEIHUA_3                    599
#define IDC_MEIHUA_4                    600
#define IDC_MEIHUA_5                    601
#define IDC_MEIHUA_6                    602
#define IDC_MEIHUA_7                    603
#define IDC_MEIHUA_8                    604
#define IDC_MEIHUA_9                    605
#define IDC_MEIHUA_10                   606
#define IDC_MEIHUA_J                    607
#define IDC_MEIHUA_Q                    608
#define IDC_MEIHUA_K                    609
#define IDC_FANGKUAI_1                  610
#define IDC_FANGKUAI_2                  611
#define IDC_FANGKUAI_3                  612
#define IDC_FANGKUAI_4                  613
#define IDC_FANGKUAI_5                  614
#define IDC_FANGKUAI_6                  615
#define IDC_FANGKUAI_7                  616
#define IDC_FANGKUAI_8                  617
#define IDC_FANGKUAI_9                  618
#define IDC_FANGKUAI_10                 619
#define IDC_FANGKUAI_J                  620
#define IDC_FANGKUAI_Q                  621
#define IDC_FANGKUAI_K                  622
#define IDC_WANG_1                      623
#define IDC_WANG_2                      624
#define IDC_CARD_1                      625
#define IDC_CARD_2                      626
#define IDC_CARD_3                      627
#define IDC_CARD_4                      628
#define IDC_DESK_0                      629
#define IDC_DESK_1                      630
#define IDC_DESK_2                      631
#define IDC_DESK_3                      632
#define IDC_DESK_4                      633
#define IDC_DESK_5                      634
#define IDC_DESK_6                      635
#define IDI_CLIENT_LIST                 1000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1050
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           1008
#endif
#endif
