//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GamePlace.rc
//
#define IDR_MANIFEST                    1
#define IDQUXIAO                        2
#define IDOK3                           2
#define IDFEEDBACK                      2
#define ID_REG_MAIL                     3
#define IDCANCEL2                       3
#define IDOK2                           3
#define IDSERVER                        3
#define IDC_LOCKQUIT                    3
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MAIN_DIALOG                 102
#define IDS_PLACE_TITLE                 102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDS_REG_KEY                     104
#define IDD_GAME_PLACE                  105
#define IDS_CONNECT_ERROR               105
#define IDD_LOGON                       106
#define IDD_LOGO_SELECT                 108
#define IDD_FIND_USER                   111
#define IDS_HTTPDOWNLOAD_FAIL_CONNECT_SERVER 111
#define IDD_PASS_CHECK                  112
#define IDS_HTTPDOWNLOAD_INVALID_SERVER_RESPONSE 112
#define IDS_HTTPDOWNLOAD_INVALID_HTTP_RESPONSE 113
#define IDD_MANAGE_DLG                  115
#define IDD_WARNNING_DLG                116
#define IDS_HTTPDOWNLOAD_RETREIVEING_FILE 116
#define IDS_HTTPDOWNLOAD_MINUTES        119
#define IDS_HTTPDOWNLOAD_MINUTES_AND_SECONDS 120
#define IDS_HTTPDOWNLOAD_BYTES          121
#define IDS_HTTPDOWNLOAD_KILOBYTES      123
#define IDD_HTTPDOWNLOAD                124
#define IDS_HTTPDOWNLOAD_MEGABYTES      125
#define IDR_HTTPDOWNLOAD_ANIMATION      126
#define IDS_HTTPDOWNLOAD_TIMELEFT       127
#define IDS_HTTPDOWNLOAD_BYTESPERSECOND 128
#define IDS_HTTPDOWNLOAD_KILOBYTESPERSECOND 129
#define IDS_HTTPDOWNLOAD_OK_TO_OVERWRITE 130
#define IDS_HTTPDOWNLOAD_FAIL_FILE_OPEN 131
#define IDS_HTTPDOWNLOAD_ABORTING_TRANSFER 132
#define IDR_MAINFRAME                   133
#define IDD_GAME_ROOM                   136
#define IDI_LIST_NOINSTALL              137
#define IDI_LIST_KIND                   138
#define IDD_CONNECT                     139
#define IDB_LOGONBK                     144
#define IDI_LOGON                       145
#define IDC_HAND                        146
#define IDI_LIST_ROOM                   151
#define IDR_FIND_MENU                   153
#define IDD_NVAIGATION                  154
#define IDD_GAME_RULE                   191
#define IDR_TALK_ATTRIB                 195
#define IDS_HTTPDOWNLOAD_FILESTATUS     202
#define IDS_HTTPDOWNLOAD_CONNECTED      203
#define IDS_HTTPDOWNLOAD_RESOLVING_NAME 204
#define IDS_HTTPDOWNLOAD_RESOLVED_NAME  205
#define IDS_HTTPDOWNLOAD_CONNECTING     206
#define IDS_HTTPDOWNLOAD_REDIRECTING    207
#define IDS_HTTPDOWNLOAD_GETTING_FILE_INFORMATION 208
#define IDS_HTTPDOWNLOAD_FAIL_PARSE_ERROR 209
#define IDS_HTTPDOWNLOAD_GENERIC_ERROR  210
#define IDD_REGISTER_NEW_USER           212
#define IDS_HTTPDOWNLOAD_ERROR_READFILE 214
#define IDI_LIST_NONAME                 215
#define IDS_HTTPDOWNLOAD_PERCENTAGE     215
#define IDD_GAME_SET                    217
#define IDS_HTTPDOWNLOAD_OF             217
#define IDS_HTTPDOWNLOAD_SECONDS        218
#define IDI_CHECKOFF                    233
#define IDI_CHECKON                     234
#define IDD_CALL_GM                     245
#define IDD_FINDNULLDESK                246
#define IDD_DIALOGBANK                  247
#define IDD_DLG_CHECKOUT                248
#define IDD_DLG_CHECKIN                 249
#define IDD_SETDESKBPDLG                251
#define IDD_ROOM_RIGHT_WND              252
#define IDD_LEFT_WND                    253
#define IDD_LOGOUPLOAD                  254
#define IDD_CHECKPSW                    255
#define IDD_CHATTING                    257
#define IDD_QUIT_ASK                    258
#define IDD_DLG_TRANSFERMONEY           259
#define IDD_IM_MAIN                     260
#define IDB_IM_LIST                     261
#define IDD_IM_SESSION                  262
#define IDD_IM_SETUSER                  264
#define IDD_SOFTKEY                     266
#define IDD_BULLETIN                    267
#define IDD_DIALOG1                     275
#define IDD_WEB_WND                     275
#define IDD_PROPPANNEL                  277
#define IDD_BOARDCAST                   279
#define IDD_DIALOG2                     280
#define IDD_PERSONALSET                 280
#define IDD_PASS_DESK                   282
#define IDD_DIALOG3                     283
#define IDD_EXTROBOT                    283
#define IDD_DLG_APPEAL                  284
#define IDI_ICON1                       285
#define IDD_VIPDLG                      288
#define IDD_LOCK_ACCOUNT                289
#define IDD_BANK                        290
#define IDD_QUEUE_ROOM                  291
#define IDI_LIST_ROOM_LOCK              292
#define IDD_GAME_ROOM_PW                293
#define IDB_BITMAP1                     294
#define IDB_BITMAP2                     295
#define IDB_BITMAP3                     296
#define IDB_BITMAP4                     297
#define IDB_BITMAP5                     298
#define IDB_BITMAP6                     299
#define IDB_BITMAP7                     300
#define IDD_DIALOG4                     301
#define IDD_DLG_GMLIST                  302
#define IDD_IE                          303
#define IDD_IEAD                        303
#define IDB_BITMAP8                     304
#define IDD_DIG_ITEM                    310
#define IDB_BITMAP9                     322
#define IDD_DIALOG5                     324
#define IDD_GETHELPMONEY                324
#define IDD_DIALOG6                     326
#define IDD_ROOMFEE                     326
#define IDD_DIALOG7                     327
#define IDD_GAMELIST_TIP                328
#define IDI_BLACK                       330
#define IDI_FRIEND                      331
#define IDI_PLAYER                      332
#define IDI_UNKOWN                      333
#define IDI_UNKNOWN                     334
#define IDB_BITMAP10                    335
#define IDB_SCROLL                      336
#define IDI_LIST_KIND2                  337
#define IDD_DIALOG8                     338
#define IDD_DIALOG9                     339
#define IDD_DIALOG10                    340
#define IDD_DIALOG11                    341
#define IDD_USER_                       342
#define IDD_USER_DETAILS                343
#define IDC_EDIT_NICK                   800
#define IDC_EDIT2                       801
#define IDC_EDIT_EMAIL                  801
#define IDC_BUYCOUNT                    801
#define IDC_EDIT_PHONE_NUM              801
#define IDC_ETREGPW                     801
#define IDC_ETBCONNOIN                  801
#define IDC_EDIT3                       802
#define IDC_GIVEUSER                    802
#define IDC_EDIT_APPEAL_EMAIL           802
#define IDC_ETTIP                       802
#define IDC_EDIT4                       803
#define IDC_GIVECOUNT                   803
#define IDC_EDIT_APPEAL_CONTENT         803
#define IDC_ETCOINNUM                   803
#define IDC_EDIT5                       804
#define IDC_ETTRANSNUM                  804
#define IDC_ETBPWIN                     805
#define IDC_STATIC_4                    900
#define IDC_STATIC_5                    901
#define IDC_STATIC_6                    902
#define IDC_STATIC_7                    903
#define IDC_STATIC_8                    904
#define IDC_ANIMATE1                    1000
#define IDC_STATUS                      1001
#define IDC_FILESTATUS                  1002
#define IDC_PROGRESS1                   1003
#define IDC_SPLIT_BAR                   1004
#define IDC_TIME                        1004
#define IDC_TIMELEFT                    1004
#define IDC_GAME_LIST                   1005
#define IDC_HOR_SPLIT                   1005
#define IDC_VFRAME                      1005
#define IDC_TRANSFER_RATE               1005
#define IDC_HFRAME                      1006
#define IDC_QUIT                        1006
#define IDC_HFRAME2                     1007
#define IDC_HIDE_LIST                   1008
#define IDC_HIDE_NEWS                   1009
#define IDC_TEXT                        1010
#define IDC_PASS                        1011
#define IDC_BIND_USER                   1011
#define IDC_BIND_GAME                   1012
#define IDC_NAME_INFO                   1013
#define IDC_NAME                        1013
#define IDC_BIND_ROOM                   1013
#define IDC_ACC_INFO                    1014
#define IDC_ACCID                       1014
#define IDC_USER_LIST                   1015
#define IDC_MOBILE_INFO                 1015
#define IDC_VOR_SPLIT                   1016
#define IDC_KIND_NAME                   1016
#define IDC_USER_LIST2                  1016
#define IDC_FRIEND_LIST                 1016
#define IDC_FRIEND_LIST_NOUSE           1016
#define IDC_DELETE                      1017
#define IDC_USER_FRIEND                 1017
#define IDC_WARNNING_MSG                1017
#define IDC_KIND_NAME2                  1018
#define IDC_USER_NAME                   1020
#define IDC_EXPRESSION                  1021
#define IDC_LIST                        1022
#define IDC_LIST_FIND                   1022
#define IDC_GAME_FACE                   1023
#define IDC_FIND                        1024
#define IDC_SAVE_TALK                   1027
#define IDC_SET_PASS                    1029
#define IDC_REM_PASS                    1034
#define IDC_USER_PROXY                  1035
#define IDC_ACCOUNTS                    1036
#define IDC_ACC                         1037
#define IDC_REGISTER                    1039
#define IDC_REGISTER2                   1040
#define IDC_FIRE                        1040
#define IDC_APPLY_PASSWORD              1040
#define IDC_MOBILE                      1041
#define IDC_SELECT_LOGO                 1042
#define IDC_FIND_PASSWORD               1042
#define IDC_BOY                         1043
#define IDC_GIRL                        1044
#define IDC_LOGO_DISPLAY                1045
#define IDC_TALK_MESSAGE                1048
#define IDC_WEB                         1050
#define IDC_WEB2                        1051
#define IDC_WEB3                        1052
#define IDC_PROXY_SERVER                1057
#define IDC_SERVER_PORT                 1059
#define IDC_ROOM_SET                    1059
#define IDC_PROXY_NAME                  1060
#define IDC_PROXY_PASS                  1061
#define IDC_SHOW_USER                   1062
#define IDC_LIMIT_CUT                   1065
#define IDC_LIMIT_POINT                 1067
#define IDC_SAME_IP                     1069
#define IDC_HIDE_RIGHT                  1072
#define IDC_SOCKS4                      1076
#define IDC_SOCKS5                      1077
#define IDC_USE_PASS                    1078
#define IDC_ROOM_TALK                   1078
#define IDC_GAME_TALK                   1079
#define IDC_SEND_MSG                    1080
#define IDC_PLAY_GAME                   1081
#define IDC_BUTTON_MIN                  1082
#define IDC_WATCH_GAME                  1082
#define IDC_BUTTON_CLOSE                1083
#define IDC_CUT_COUNT                   1084
#define IDC_STATIC_2                    1085
#define IDC_LOW_POINT                   1086
#define IDC_STATIC_3                    1086
#define IDC_HIGH_POINT                  1087
#define IDC_INVALI_ALL                  1090
#define IDC_FRIEND_INVALI               1091
#define IDC_SHOWMENU                    1091
#define IDC_SIT                         1091
#define IDC_CHECK                       1091
#define IDC_CHECKOUT                    1091
#define IDC_CHAT                        1091
#define IDC_MOVEUP                      1091
#define IDC_NO_INVALI                   1092
#define IDC_TAB1                        1092
#define IDC_INV                         1092
#define IDC_INVITE_PLAY                 1092
#define IDC_WATCH                       1093
#define IDC_NO_SHOW_MSG                 1094
#define IDC_SERVER_LIST                 1095
#define IDC_IPADDRESS1                  1102
#define IDC_TAB2                        1103
#define IDC_STATIC_1                    1104
#define IDC_BUTTON_BT1                  1106
#define IDC_CLOSESESSION                1106
#define IDC_BUTTON_BT2                  1107
#define IDC_BUTTON_BT3                  1108
#define IDC_BUTTON_BT4                  1109
#define IDC_BUTTON_BT5                  1110
#define IDC_top_text                    1111
#define IDC_FLASH                       1112
#define IDC_EXPLORER1                   1113
#define IDC_RESTORE                     1114
#define IDC_BT6                         1115
#define IDC_BT7                         1116
#define IDC_ST1                         1117
#define IDC_ST2                         1118
#define IDC_ST3                         1119
#define IDC_ST4                         1120
#define IDC_ST5                         1121
#define IDC_ST6                         1122
#define IDC_ST7                         1123
#define IDC_DESKPAGEUP                  1126
#define IDC_DESKPAGEDOWN                1127
#define IDC_LISTPAGEDOWN                1128
#define IDC_LISTPAGEUP                  1129
#define IDC_COPYRIGHT                   1131
#define IDC_STATIC1                     1132
#define IDC_STATIC2                     1133
#define IDC_STATIC3                     1134
#define IDC_STATIC10                    1135
#define IDC_STATIC5                     1136
#define IDC_CODE                        1137
#define IDC_PASS_2                      1138
#define IDC_EDIT7                       1139
#define IDC_TRANSFER_NAME               1139
#define IDC_ETCHPW                      1139
#define IDC_STATIC6                     1140
#define IDC_GM_CHECK1                   1141
#define IDC_GM_GAME_ERROR               1141
#define IDC_HOR_SPLIT2                  1141
#define IDC_CHECK2                      1142
#define IDC_GM_CHECK2                   1142
#define IDC_GM_COURT                    1142
#define IDC_BT1                         1142
#define IDC_TWO                         1142
#define IDC_GM_MSG                      1143
#define IDC_BT2                         1143
#define IDC_CHECK1                      1144
#define IDC_IP_PLAY                     1144
#define IDC_BT3                         1144
#define IDC_ONE                         1144
#define IDC_PPOISON                     1144
#define IDC_CHECK_TRANS_ALL             1144
#define IDC_BT4                         1145
#define IDC_BT8                         1146
#define IDC_BT9                         1147
#define IDC_BT10                        1148
#define IDC_BT11                        1149
#define IDC_CUSTOM2                     1150
#define IDC_BT12                        1150
#define IDC_BT13                        1151
#define IDC_BT14                        1152
#define IDC_BUTTON13                    1153
#define IDC_BT15                        1153
#define IDC_STATIC8                     1154
#define IDC_BT16                        1154
#define IDC_STATIC4                     1155
#define IDC_STATIC_16                   1155
#define IDC_STATIC7                     1156
#define IDC_STATIC9                     1157
#define IDC_STATIC_17                   1158
#define IDC_STATIC11                    1158
#define IDC_STATIC12                    1159
#define IDC_STATIC_15                   1159
#define IDC_SKIN                        1160
#define IDC_CHECKIN                     1160
#define IDC_MOVELEFT                    1160
#define IDC_PUBLICPOISON                1161
#define IDC_QUERY                       1161
#define IDC_CHECK4                      1162
#define IDC_OTHERS                      1162
#define IDC_NULL                        1162
#define IDC_UPTWO                       1163
#define IDC_EDIT_MONEY                  1164
#define IDC_EDIT_CHECKOUT               1167
#define IDC_EDIT_CHECKIN                1168
#define IDC_OUTROOM                     1170
#define IDC_EDIT                        1171
#define IDC_INROOM                      1171
#define IDC_ETCOIN                      1171
#define IDC_EDIT_MONEY_ROOM             1172
#define IDC_BTN_HALL2                   1173
#define IDC_EDIT_MONEY_BEILV            1173
#define IDC_STATIC_PROMPT               1180
#define IDC_BTN_HALL1                   1181
#define IDC_RADIO_0                     1182
#define IDC_RADIO_1                     1183
#define IDC_IP_LIMITE                   1183
#define IDC_BTN_HALL3                   1183
#define IDC_MOVEDOWN                    1183
#define IDC_RADIO_10                    1184
#define IDC_BTN_HALL4                   1184
#define IDC_MOVERIGHT                   1184
#define IDC_RADIO_100                   1185
#define IDC_BTN_HALL5                   1185
#define IDC_LOADIMAGE                   1185
#define IDC_RADIO_500                   1186
#define IDC_EDIT_INPUT                  1186
#define IDC_BTN_HALL6                   1186
#define IDC_UPLOAD                      1186
#define IDC_RADIO_200                   1187
#define IDC_MSG                         1187
#define IDC_BTN_HALL7                   1187
#define IDC_RADIO_1000                  1188
#define IDC_BTN_HALL8                   1188
#define IDC_EDIT_TWOPSW                 1188
#define IDC_RADIO_2000                  1189
#define IDC_BTN_HALL9                   1189
#define IDC_STATIC_TITLE                1189
#define IDC_SMALLIMAGE                  1189
#define IDC_RADIO_5000                  1190
#define IDC_BTN_HALL10                  1190
#define IDC_STATIC_13                   1190
#define IDC_LARGEIMAGE                  1190
#define IDC_RADIO_10000                 1191
#define IDC_BTN_HALLMIN                 1191
#define IDC_STATIC_11                   1191
#define IDC_RESET                       1191
#define IDC_BTN_HALLMAX                 1192
#define IDC_STATIC_12                   1192
#define IDC_STATE                       1192
#define IDC_BTN_HALLRESTORE             1193
#define IDC_STATIC_23                   1193
#define IDC_BTN_HALLSKIN                1194
#define IDC_HELP_LIST                   1194
#define IDC_BTN_HALLCLOSE               1195
#define IDC_EDIT_RECOMMENDER            1195
#define IDC_IE_VIEW                     1196
#define IDC_STATIC_18                   1196
#define IDC_CHANGEID                    1197
#define IDC_BTN                         1197
#define IDC_BTN_TRANSFER                1197
#define IDC_TRANSFER_MONEY              1198
#define IDC_STATIC_9                    1199
#define IDC_COMBO1                      1200
#define IDC_STATIC_19                   1201
#define IDC_TREE1                       1202
#define IDC_CHATMSG                     1203
#define IDC_INPUT                       1204
#define IDC_BUTTON1                     1205
#define IDC_SEND                        1205
#define IDC_CLOSEIM                     1205
#define IDC_CLOSELOGO                   1205
#define IDC_SOFTKEY                     1205
#define IDC_COMBOFONTSIZE               1206
#define IDC_BUTTON2                     1206
#define IDC_COMBOFONTNAME               1207
#define IDC_BUTTON3                     1207
#define IDC_COMBOCOLOR                  1208
#define IDC_BUTTON4                     1208
#define IDC_SENDKEY                     1209
#define IDC_BUTTON5                     1209
#define IDC_SENDSTATE                   1210
#define IDC_BUTTON6                     1210
#define IDC_EDIT1                       1211
#define IDC_BUTTON7                     1211
#define IDC_BUTTON8                     1212
#define IDC_EDIT_GAMECOIN               1212
#define IDC_PW_CONFIRM                  1212
#define IDC_MINISIZE                    1213
#define IDC_BUTTON9                     1213
#define IDC_EDIT_BOXCOIN                1213
#define IDC_BUTTON10                    1214
#define IDC_ETOUTCOIN                   1214
#define IDC_BUTTON11                    1215
#define IDC_ETOTHERID                   1215
#define IDC_BUTTON12                    1216
#define IDC_PICCUT                      1216
#define IDC_ETPW                        1216
#define IDC_BUTTON14                    1217
#define IDC_PICSCALE                    1217
#define IDC_EDIT_GAMECOIN2              1217
#define IDC_BUTTON15                    1218
#define IDC_WEBBROWSER                  1218
#define IDC_EDIT_BOXCOIN2               1218
#define IDC_BUTTON16                    1219
#define IDC_ETBOXCOIN                   1219
#define IDC_BUTTON17                    1220
#define IDC_ETBCONNO                    1220
#define IDC_BUTTON18                    1221
#define IDC_PAUSE                       1221
#define IDC_ETBPW                       1221
#define IDC_BUTTON19                    1222
#define IDC_PLAY                        1222
#define IDC_BUTTON20                    1223
#define IDC_VOLDOWN                     1223
#define IDC_BUTTON21                    1224
#define IDC_VOLUP                       1224
#define IDC_USE                         1225
#define IDC_SUPPORT                     1225
#define IDC_BUTTON23                    1226
#define IDC_BUY                         1226
#define IDC_BUTTON24                    1227
#define IDC_GIVE                        1227
#define IDC_BUTTON25                    1228
#define IDC_TIP                         1228
#define IDC_BUTTON26                    1229
#define IDC_CLOSE                       1229
#define IDC_BUTTON27                    1230
#define IDC_HOLDCOUNT                   1230
#define IDC_BUTTON28                    1231
#define IDC_NEEDMONEY                   1231
#define IDC_BUTTON29                    1232
#define IDC_PROPBUY                     1232
#define IDC_BUTTON30                    1233
#define IDC_PROPPREV                    1233
#define IDC_BUTTON31                    1234
#define IDC_PROP1                       1234
#define IDC_BUTTON32                    1235
#define IDC_PROP2                       1235
#define IDC_BUTTON33                    1236
#define IDC_PROP3                       1236
#define IDC_BUTTON34                    1237
#define IDC_PROPNEXT                    1237
#define IDC_BUTTON35                    1238
#define IDC_BUTTON36                    1239
#define IDC_EDIT_USERNAME               1239
#define IDC_BUTTON37                    1240
#define IDC_BUTTON38                    1241
#define IDC_BUTTON39                    1242
#define IDC_BUTTON40                    1243
#define IDC_LIST3                       1243
#define IDC_BUTTON41                    1244
#define IDC_LIST1                       1244
#define IDC_BUTTON42                    1245
#define IDC_CLODE                       1245
#define IDC_BUTTON43                    1246
#define IDC_BANK_PWD                    1246
#define IDC_BUTTON44                    1247
#define IDC_STATIC_TIP                  1247
#define IDC_BUTTON45                    1248
#define IDC_CHECK_NUM                   1248
#define IDC_BUTTON46                    1249
#define IDC_UNIT                        1249
#define ID_NOQUEUE                      1249
#define IDC_BUTTON47                    1250
#define IDC_STATIC_BANK                 1250
#define ID_QUEUE                        1250
#define IDC_BUTTON48                    1251
#define IDC_STATIC_WALLET               1251
#define ID_EXIT                         1251
#define IDC_Shift                       1252
#define IDC_STATIC_COUNT                1252
#define IDC_CAPLOCK                     1253
#define IDC_STATIC_BCOIN                1253
#define IDC_NEWHELP                     1254
#define IDC_STATIC_WCOIN                1254
#define IDC_STATIC_CALL                 1255
#define IDC_STATIC_MSG                  1256
#define IDC_STATIC_GMCALL               1257
#define IDC_STATIC_SEARCH               1258
#define IDC_STATIC_BP                   1259
#define IDC_STATIC_HEAD                 1260
#define IDC_STATIC_NOTE                 1261
#define IDC_STATIC_POS                  1262
#define IDC_STATE_UN                    1263
#define IDC_STATIC_AU                   1264
#define IDC_STATIC_USERNAME             1265
#define IDC_STATIC_OPNOTE               1266
#define IDC_STATIC_OWN                  1267
#define IDC_STATIC_BUY                  1268
#define IDC_STATIC_GIF                  1269
#define IDC_STATIC_NO                   1270
#define IDC_BTNCLOSE                    1271
#define IDC_BTNINFOR                    1272
#define IDC_BTNTRANSFER                 1273
#define IDC_BTNRECORD                   1274
#define IDC_BTNSAFE                     1275
#define IDC_BTNPW                       1276
#define IDC_EDIT_INFO_GOLD              1277
#define IDC_BTN_TRANOK                  1278
#define IDC_EDIT_INFO_GOLD2             1279
#define IDC_SKINLIST                    1280
#define IDC_BTNREFRESH                  1281
#define IDC_BTNBOK                      1282
#define IDC_BTNBACTIVE                  1283
#define IDC_BTNBCHARGE                  1284
#define IDC_ETACOIN                     1285
#define IDC_ETBREGPW                    1286
#define IDC_RSAVE                       1287
#define IDC_RGET                        1288
#define IDC_BTNCHGOK                    1289
#define IDC_BTNCHGCLOSE                 1290
#define IDC_ETOLDPW                     1291
#define IDC_ETOLDPWIN                   1292
#define IDC_ETNEWPW                     1293
#define IDC_ETNEWPWIN                   1294
#define IDC_ETCONFIRM                   1295
#define IDC_ETNEWPWIN2                  1296
#define IDC_ETCONFIRMIN                 1296
#define IDC_PW                          1299
#define IDC_BUTTON_QUIT                 1300
#define IDC_STATIC_TXT                  1301
#define IDC_STATICTO                    1302
#define IDC_BTN_TRANS_ALL               1303
#define IDC_BUTTON_LEFT_ARROW           1303
#define IDC_BUTTON_RIGHT_ARROW          1304
#define IDC_BUTTON_PROP1                1305
#define IDC_BUTTON_PROP2                1306
#define IDC_BUTTON_PROP3                1307
#define IDC_PROP4                       1308
#define IDC_PROP5                       1309
#define IDC_PROP6                       1310
#define IDC_PROP7                       1311
#define IDC_PROP8                       1312
#define IDC_ETUSERCOIN                  1313
#define IDC_ETTRANSCOIN                 1314
#define IDC_ETNUMTOCHINESE              1315
#define IDC_EDIT13                      1316
#define IDC_EDIT11                      1321
#define IDC_EDIT6                       1322
#define IDC_MONEY_STATIC                1323
#define IDC_MONEY                       1324
#define IDC_ET_MONEY                    1324
#define IDC_EDITTEXT                    1326
#define IDC_WEB_VIEW                    1327
#define IDC_ROOM_INFO                   1328
#define IDC_ROOM_OK                     1329
#define IDC_BUTTON_CANCLE               1329
#define IDC_STATIC_INFOMATION           1330
#define IDC_BUTTON_NEXT                 1331
#define IDC_CHECK_NOTIFY                1332
#define IDC_CLOSEBTN                    1339
#define IDC_MINSESSION                  1340
#define IDC_BTN_CLOSE                   1341
#define IDC_BTN_COIN_ALL                1342
#define IDC_ETSECONDPW                  1500
#define IDC_ETTRANSUSERID               1501
#define IDI_CONNECT                     2009
#define IDC_FALSH                       2015
#define IDC_BEGINAGREE                  2016
#define IDC_BTN_LIST1                   2016
#define IDC_BTN_LIST2                   2017
#define IDC_BTN_LIST3                   2018
#define IDC_BTN_LIST4                   2019
#define IDC_SELECT_COLOR                2019
#define IDC_BTN_ROOM1                   2021
#define IDC_BTN_ROOM2                   2022
#define IDC_BTN_ROOM3                   2023
#define IDC_BTN_ROOM4                   2024
#define IDC_BTN_ROOM5                   2025
#define IDC_BTN_ROOM6                   2026
#define IDC_BTN_ROOM7                   2027
#define IDC_BTN_ROOM8                   2028
#define IDC_BTN_ROOM9                   2029
#define IDC_BTN_ROOM10                  2030
#define IDC_INFORSTR                    2096
#define IDC_BUTTON_CHONGZHI             2098
#define IDC_BUTTON_GAMELIST             2099
#define IDC_BTN_MAIN1                   3031
#define IDC_BTN_MAIN2                   3032
#define IDC_BTN_MAIN3                   3033
#define IDC_BTN_MAIN4                   3034
#define IDC_BTN_MAIN5                   3035
#define IDC_BTN_MAIN6                   3036
#define IDC_BTN_MAIN7                   3037
#define IDC_BTN_MAIN8                   3038
#define IDC_BTN_MAIN9                   3039
#define IDC_BTN_MAIN10                  3040
#define IDC_EXPLORER2                   3041
#define IDC_IM_LIST                     3042
#define IDC_RTRANS_ID                   3043
#define IDC_RTRANS_NN                   3044
#define IDC_LIST2                       3045
#define IDC_RADIO1                      3046
#define IDC_RADIO2                      3047
#define IDC_RADIO3                      3048
#define IDC_RADIO4                      3049
#define IDC_RADIO5                      3050
#define IDC_CUSTOM1                     3051
#define IDC_CHATTING                    10005
#define IDC_EXPLORER10                  10220
#define IDC_ETCHINESE                   13111
#define IDI_LIST_ROOT                   32533
#define IDM_FIND_ONLINE_USER            32778
#define IDM_FIND_DESK                   32780
#define IDM_CUSTOM_FIND_DESK            32781
#define IDM_FINDED_SIT                  32782
#define IDM_TALK_COLOR                  32793
#define IDM_RED                         32794
#define IDM_YELLOW                      32795
#define IDM_BULE                        32796
#define IDM_GREEN                       32797
#define IDM_WHITE                       32798
#define IDM_POWER_RED                   32799
#define IDM_GRAY                        32800
#define IDM_SAVE_MESSAGE                32801
#define IDM_CLEAR_SCREEN                32803
#define IDM_AUTO_SCROLL                 32804
#define IDM_GIVE_PROP                   32805
#define IDC_BTN_GAMELIST                32806
#define IDC_BTN_CHONGZHILIST            32807
#define IDC_FUN_LIST                    32808
#define IDC_BTN_IMLIST                  32809
#define IDC_BTN_USERINFO                32810
#define IDC_BTN_FACSX                   32811
#define IDC_BTN_Mail	                32812
#define IDC_BTN_Rule	                32813
#define IDC_BTN_Contest	                32814
#define IDC_BTN_Finance	                32815
#define IDC_BTN_LOGO					32816

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        338
#define _APS_NEXT_COMMAND_VALUE         32806
#define _APS_NEXT_CONTROL_VALUE         3045
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
